# @env = dev
### create new mission
# @prompt mission_name Mission Name
# @prompt description Mission Description
POST {{base_url}}/missions-management
Content-Type: application/json
Authorization: Bearer {{menta_token}}


{
    "name": "{{mission_name}}",
    "description":"{{description}}"
}


### update mission
# @prompt mission_id Mission ID
# @prompt mission_name Mission Name
# @prompt description Mission Description
PATCH {{base_url}}/missions-management/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{menta_token}}


{
    "name": "{{mission_name}}",
    "description": "{{description}}"
}


### remove mission
# @prompt mission_id Mission ID
DELETE {{base_url}}/missions-management/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{menta_token}}


//! Mission Operation
// ทำสอบ api ใน server/api tests/mission_test.http
### set mission to in-progress
# @prompt mission_id Mission ID to Set In-Progress
PATCH  {{base_url}}/mission/in-progress/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{menta_token}}


### set mission to completed
# @prompt mission_id Mission ID to Set Completed
PATCH  {{base_url}}/mission/to-completed/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{menta_token}}


### set mission to failed
# @prompt mission_id Mission ID to Set Failed
PATCH  {{base_url}}/mission/to-failed/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{menta_token}}


# Mission Viewing
### get mission by id
# @prompt mission_id Mission ID
GET  {{base_url}}/view/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{menta_token}}



### get missions with name
# @prompt name Name to Search
GET  {{base_url}}/view/gets?name={{name}}
Content-Type: application/json
Authorization: Bearer {{menta_token}}


### get missions with name and status
# @prompt name Name to Search
# @prompt status Status to Search
GET  {{base_url}}/view/gets?name={{name}}&status={{status}}
Content-Type: application/json
Authorization: Bearer {{menta_token}}

